services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    volumes:
      - ./config.yaml:/etc/livekit.yaml
    ports:
      - "7880:7880"   # HTTP API
      - "7881:7881"   # gRPC API
      - "52000-60000:52000-60000/udp" # Media UDP ports
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    networks:
      - rk3588-network

  session-manager:
    build:
      context: ./session-manager
      dockerfile: Dockerfile
    container_name: session-manager
    volumes:
      - ./session-manager/config/docker.toml:/etc/session-manager/config.toml
    ports:
      - "8080:8080"   # Session Manager API
    depends_on:
      - livekit
    restart: unless-stopped
    networks:
      - rk3588-network
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 10s
      retries: 3

networks:
  rk3588-network:
    external: true
    name: rk3588-network