services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    volumes:
      - ./config.yaml:/etc/livekit.yaml
    network_mode: host
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -ln | grep :7880 || ss -ln | grep :7880"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  session-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: session-manager
    volumes:
      - ./session-manager/config/docker.toml:/etc/session-manager/config.toml
    network_mode: host
    depends_on:
      livekit:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - RUST_LOG=session_manager=info,microservice_sdk=info,livekit=info,livekit_api=info,tower_http=info
      - RUST_BACKTRACE=1
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devkey_secret_that_is_at_least_32_characters_long_for_security
      - LIVEKIT_SERVER_URL=ws://localhost:7880
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
