services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    volumes:
      - ./config.yaml:/etc/livekit.yaml
    network_mode: host
    command: --config /etc/livekit.yaml
    restart: unless-stopped

  session-manager:
    build:
      context: ./session-manager
      dockerfile: Dockerfile
    container_name: session-manager
    volumes:
      - ./session-manager/config/docker.toml:/etc/session-manager/config.toml
    network_mode: host
    depends_on:
      - livekit
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 10s
      retries: 3
