[server]
host = "0.0.0.0"
port = 8765
workers = 4

[livekit]
server_url = "ws://localhost:7880"
api_key = "devkey"
api_secret = "devkey_secret_that_is_at_least_32_characters_long_for_security"

[microservices]
registration_timeout = 30
join_timeout = 60

[logging]
level = "debug"
format = "json"

[vector_log]
enabled = true
endpoint = "localhost:9000"
source_name = "session-manager"