[server]
host = "127.0.0.1"
port = 8080
workers = 4

[livekit]
server_url = "http://localhost:7880"
api_key = "devkey"
api_secret = "secret"

[microservices]
registration_timeout = 30
join_timeout = 60

[logging]
level = "trace"
format = "pretty"

[vector_log]
enabled = false
endpoint = "http://localhost:8686"
source_name = "session-manager"